---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: droit-deployment
  labels:
    app: droit
    env: test
spec:
  replicas: 3
  template:
    metadata:
      name: droit-master-pod
      labels:
        app: droit-master
    spec:
      containers:
        - name: droit
          image: droit-local:1.0.0
          command: ["python3", "./run.py", "--level", "level1"]
          imagePullPolicy: Never
          env:
            - name: MONGODB_HOST
              value: mongodb-service
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password
  selector:
    matchLabels:
      app: droit-master
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: droit-master-service
# spec:
#   selector:
#     app: droit-master
#   ports:
#     - protocol: TCP
#       port: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: droit-service
spec:
  type: NodePort
  selector:
    app: droit-master
  ports:
    - port: 5002
      targetPort: 5002
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
